### ISSUE TITLE
Cannot use addSlide

### ISSUE THREAD

**Issue by Terkildsen** [iosscripts/iosslider#190]
Hi,

I'm testing the script right now. It looks very promising. However, I have one issue that I'm trying to solve. 

I can initialize the script just fine. Everything works great. But when I try to add a slide, I get the following error:
TypeError: Cannot read property 'currentSlideNumber' of undefined
    at HTMLDivElement.<anonymous> (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery.iosslider.js:2280:52)
    at Function.e.extend.each (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery-1.7.min.js:2:11819)
    at e.fn.e.each (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery-1.7.min.js:2:8381)
    at Object.methods.update (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery.iosslider.js:2273:19)
    at HTMLDivElement.<anonymous> (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery.iosslider.js:2339:13)
    at Function.e.extend.each (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery-1.7.min.js:2:11819)
    at e.fn.e.each (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery-1.7.min.js:2:8381)
    at methods.addSlide (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery.iosslider.js:2301:16)
    at $.fn.iosSlider (http://frontendimageupload.bleaudev.dk/touchswipe/js/jquery.iosslider.js:2446:27)
    at link (http://frontendimageupload.bleaudev.dk/touchswipe/js/iosSliderDirective.js:25:26) <iosslider style=""> 

My code looks like this:
            var iosSliderAPI = $('.iosSlider').iosSlider({
                //snapToChildren: true,
                scrollbar: false,
                scrollbarHide: false,
                desktopClickDrag: true
            });

```
        iosSliderAPI.iosSlider('goToSlide', 1);
        iosSliderAPI.iosSlider('addSlide', 'test', 3);
```

Please note that I'm wrapping the plugin via AngularJS. However, I tested by removing all AngularJS-stuff, and I still get the error. 

The funny part is that if I call the addSlide-method twice, the new slide is actually added. So I'm thinking that maybe it is my selector stuff that is crappy :-)

Regards

Peter

**Comment by marcwhitbread** [comment]
I just checked my benchmarks (_demos/_benchmarks/_general) vs v1.1.55 and everything seems to be adding ok. Which version are you running? 

v1.1.55: https://github.com/iosscripts/iosSlider/archive/master.zip

**Comment by Terkildsen** [comment]
Hi,

It seems that it's my AngularJS code that pollutes yours. I isolated the code, and now I can add just fine. It must be the selector that is somehow out of scope.

Sorry for bothering you. :-)

Peter

**Comment by marcwhitbread** [comment]
No problem. Glad you got everything working :).
